import { PrismaClient } from '../src/generated/prisma';

const prisma = new PrismaClient();

// Generated from BOARDER MENU ADD.xlsx (308 unique major categories)
// First occurrence used when multiple MC_CDs exist for same MAJ_CAT_NM
const MAJOR_CATEGORIES: Array<{ name: string; mcCode: string; division: string; subDivision: string }> = [
  { name: 'IBW_B_SUIT', mcCode: '141050101', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_FLC_B_SUIT', mcCode: '141050201', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_PLFL_B_SUIT', mcCode: '141050301', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_PYJAMA', mcCode: '141040101', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_SHRN_B_SUIT', mcCode: '141050401', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_SHIRT', mcCode: '141010101', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_T_SHIRT_FS', mcCode: '141030201', division: 'KIDS', subDivision: 'IB' },
  { name: 'IBW_T_SHIRT_HS', mcCode: '141030101', division: 'KIDS', subDivision: 'IB' },
  { name: 'IGW_B_SUIT', mcCode: '142050101', division: 'KIDS', subDivision: 'IG' },
  { name: 'IGW_DRESS', mcCode: '142020101', division: 'KIDS', subDivision: 'IG' },
  { name: 'IGW_FROCK', mcCode: '142010101', division: 'KIDS', subDivision: 'IG' },
  { name: 'IGW_PYJAMA', mcCode: '142030101', division: 'KIDS', subDivision: 'IG' },
  { name: 'IGW_SKIRT', mcCode: '142040101', division: 'KIDS', subDivision: 'IG' },
  { name: 'IGW_T_SHIRT_FS', mcCode: '142060201', division: 'KIDS', subDivision: 'IG' },
  { name: 'IGW_T_SHIRT_HS', mcCode: '142060101', division: 'KIDS', subDivision: 'IG' },
  { name: 'KB_BERMUDA', mcCode: '131020201', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_CARGO_BERMUDA', mcCode: '131020301', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_CARGO_TROUSER', mcCode: '131010301', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_ETHNIC_SET', mcCode: '131060601', division: 'KIDS', subDivision: 'KB-SETS' },
  { name: 'KB_FLC_HOODIE_FS', mcCode: '131050501', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_FLC_HOODIE_HS', mcCode: '131050401', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_FLC_JACKET', mcCode: '131060301', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_FLC_LOWER', mcCode: '131040301', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_FLC_SET', mcCode: '131060401', division: 'KIDS', subDivision: 'KB-SETS' },
  { name: 'KB_FLC_SWEATSHIRT', mcCode: '131050301', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_KURTA', mcCode: '131060501', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_LOWER', mcCode: '131040101', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_LOWER_JOGGER', mcCode: '131040201', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_PW_SHIRT_FS', mcCode: '131050101', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_PW_SHIRT_HS', mcCode: '131050201', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_SET', mcCode: '131060201', division: 'KIDS', subDivision: 'KB-SETS' },
  { name: 'KB_T_SHIRT_FS', mcCode: '131030201', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_T_SHIRT_HS', mcCode: '131030101', division: 'KIDS', subDivision: 'KB-U' },
  { name: 'KB_TROUSER', mcCode: '131010101', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KB_TROUSER_JOGGER', mcCode: '131010201', division: 'KIDS', subDivision: 'KB-L' },
  { name: 'KBW_FLC_HOODIE_FS', mcCode: '133050501', division: 'KIDS', subDivision: 'KBW-U' },
  { name: 'KBW_FLC_HOODIE_HS', mcCode: '133050401', division: 'KIDS', subDivision: 'KBW-U' },
  { name: 'KBW_FLC_JACKET', mcCode: '133060301', division: 'KIDS', subDivision: 'KBW-U' },
  { name: 'KBW_FLC_LOWER', mcCode: '133040301', division: 'KIDS', subDivision: 'KBW-L' },
  { name: 'KBW_FLC_SET', mcCode: '133060401', division: 'KIDS', subDivision: 'KBW-SETS' },
  { name: 'KBW_FLC_SWEATSHIRT', mcCode: '133050301', division: 'KIDS', subDivision: 'KBW-U' },
  { name: 'KBW_LOWER', mcCode: '133040101', division: 'KIDS', subDivision: 'KBW-L' },
  { name: 'KBW_LOWER_JOGGER', mcCode: '133040201', division: 'KIDS', subDivision: 'KBW-L' },
  { name: 'KBW_SET', mcCode: '133060201', division: 'KIDS', subDivision: 'KBW-SETS' },
  { name: 'KBW_T_SHIRT_FS', mcCode: '133030201', division: 'KIDS', subDivision: 'KBW-U' },
  { name: 'KBW_T_SHIRT_HS', mcCode: '133030101', division: 'KIDS', subDivision: 'KBW-U' },
  { name: 'KG_BERMUDA', mcCode: '132020201', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KG_CAPRI', mcCode: '132020301', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KG_ETHNIC_SET', mcCode: '132060601', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_FLC_HOODIE_FS', mcCode: '132050501', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_FLC_HOODIE_HS', mcCode: '132050401', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_FLC_JACKET', mcCode: '132060301', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_FLC_LOWER', mcCode: '132040201', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KG_FLC_SET', mcCode: '132060401', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_FLC_SWEATSHIRT', mcCode: '132050301', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_KURTA', mcCode: '132060501', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_LEGGING', mcCode: '132020401', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KG_LOWER', mcCode: '132040101', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KG_SET', mcCode: '132060201', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_SKIRT', mcCode: '132020101', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KG_T_SHIRT_FS', mcCode: '132030201', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_T_SHIRT_HS', mcCode: '132030101', division: 'KIDS', subDivision: 'KG-U' },
  { name: 'KG_TROUSER', mcCode: '132010101', division: 'KIDS', subDivision: 'KG-L' },
  { name: 'KGW_FLC_HOODIE_FS', mcCode: '134050501', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_FLC_HOODIE_HS', mcCode: '134050401', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_FLC_JACKET', mcCode: '134060301', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_FLC_LOWER', mcCode: '134040201', division: 'KIDS', subDivision: 'KGW-L' },
  { name: 'KGW_FLC_SET', mcCode: '134060401', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_FLC_SWEATSHIRT', mcCode: '134050301', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_LOWER', mcCode: '134040101', division: 'KIDS', subDivision: 'KGW-L' },
  { name: 'KGW_SET', mcCode: '134060201', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_T_SHIRT_FS', mcCode: '134030201', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_T_SHIRT_HS', mcCode: '134030101', division: 'KIDS', subDivision: 'KGW-U' },
  { name: 'KGW_TROUSER', mcCode: '134010101', division: 'KIDS', subDivision: 'KGW-L' },
  { name: 'KI_BERMUDA', mcCode: '135020201', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_FLC_HOODIE_FS', mcCode: '135050501', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_FLC_HOODIE_HS', mcCode: '135050401', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_FLC_JACKET', mcCode: '135060301', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_FLC_LOWER', mcCode: '135040201', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_FLC_SET', mcCode: '135060401', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_FLC_SWEATSHIRT', mcCode: '135050301', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_LOWER', mcCode: '135040101', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_LOWER_JOGGER', mcCode: '135040301', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_SET', mcCode: '135060201', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_T_SHIRT_FS', mcCode: '135030201', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_T_SHIRT_HS', mcCode: '135030101', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_TROUSER', mcCode: '135010101', division: 'KIDS', subDivision: 'KI' },
  { name: 'KI_TROUSER_JOGGER', mcCode: '135010201', division: 'KIDS', subDivision: 'KI' },
  { name: 'KIW_FLC_HOODIE_FS', mcCode: '136050501', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_FLC_HOODIE_HS', mcCode: '136050401', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_FLC_JACKET', mcCode: '136060301', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_FLC_LOWER', mcCode: '136040201', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_FLC_SET', mcCode: '136060401', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_FLC_SWEATSHIRT', mcCode: '136050301', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_LOWER', mcCode: '136040101', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_SET', mcCode: '136060201', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_T_SHIRT_FS', mcCode: '136030201', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_T_SHIRT_HS', mcCode: '136030101', division: 'KIDS', subDivision: 'KIW' },
  { name: 'KIW_TROUSER', mcCode: '136010101', division: 'KIDS', subDivision: 'KIW' },
  { name: 'L_BERMUDA', mcCode: '211020201', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_CAPRI', mcCode: '211020301', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_DRESS', mcCode: '211060201', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_ETHNIC_DUPATTA', mcCode: '211100101', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_ETHNIC_JACKET', mcCode: '211070301', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_ETHNIC_LEGGING', mcCode: '211090201', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_ETHNIC_PALAZZO', mcCode: '211090301', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_ETHNIC_SALWAR', mcCode: '211090101', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_ETHNIC_SET', mcCode: '211080101', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_FLC_HOODIE_FS', mcCode: '211050501', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_FLC_HOODIE_HS', mcCode: '211050401', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_FLC_JACKET', mcCode: '211060301', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_FLC_LOWER', mcCode: '211040201', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_FLC_SWEATSHIRT', mcCode: '211050301', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_KURTA_FS', mcCode: '211070101', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_KURTA_HS', mcCode: '211070201', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_KURTI_FS', mcCode: '211070401', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_KURTI_HS', mcCode: '211070501', division: 'LADIES', subDivision: 'LK&L' },
  { name: 'L_LEGGING', mcCode: '211020401', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_LINGERIE', mcCode: '211110201', division: 'LADIES', subDivision: 'LN&L' },
  { name: 'L_LOWER', mcCode: '211040101', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_LOWER_JOGGER', mcCode: '211040301', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_NIGHTY', mcCode: '211110101', division: 'LADIES', subDivision: 'LN&L' },
  { name: 'L_SHIRT_FS', mcCode: '211030101', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_SHIRT_HS', mcCode: '211030201', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_SHORTS', mcCode: '211020101', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_SKIRT', mcCode: '211020501', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_T_SHIRT_FS', mcCode: '211010201', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_T_SHIRT_HS', mcCode: '211010101', division: 'LADIES', subDivision: 'LU' },
  { name: 'L_TROUSER', mcCode: '211020601', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_TROUSER_JOGGER', mcCode: '211020701', division: 'LADIES', subDivision: 'LL' },
  { name: 'L_TUNIC_FS', mcCode: '211060101', division: 'LADIES', subDivision: 'LU' },
  { name: 'LW_BERMUDA', mcCode: '212020101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_DRESS', mcCode: '212060201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_ETHNIC_JACKET', mcCode: '212070301', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_ETHNIC_LEGGING', mcCode: '212090201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_ETHNIC_PALAZZO', mcCode: '212090301', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_ETHNIC_SALWAR', mcCode: '212090101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_ETHNIC_SET', mcCode: '212080101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_FLC_HOODIE_FS', mcCode: '212050501', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_FLC_HOODIE_HS', mcCode: '212050401', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_FLC_JACKET', mcCode: '212060301', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_FLC_LOWER', mcCode: '212040201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_FLC_SWEATSHIRT', mcCode: '212050301', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_KURTA_FS', mcCode: '212070101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_KURTA_HS', mcCode: '212070201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_KURTI_FS', mcCode: '212070401', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_KURTI_HS', mcCode: '212070501', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_LEGGING', mcCode: '212020201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_LOWER', mcCode: '212040101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_LOWER_JOGGER', mcCode: '212040301', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_SHIRT_FS', mcCode: '212030101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_SHIRT_HS', mcCode: '212030201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_SHORTS', mcCode: '212010101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_SKIRT', mcCode: '212020301', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_T_SHIRT_FS', mcCode: '212000201', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_T_SHIRT_HS', mcCode: '212000101', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_TROUSER', mcCode: '212020401', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_TROUSER_JOGGER', mcCode: '212020501', division: 'LADIES', subDivision: 'LW' },
  { name: 'LW_TUNIC_FS', mcCode: '212060101', division: 'LADIES', subDivision: 'LW' },
  { name: 'M_BERMUDA_HS', mcCode: '113030101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_BERMUDA_HS_CARGO', mcCode: '113030201', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_CAPRI_HS', mcCode: '113030301', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_CARGO_TROUSER_FS', mcCode: '112030301', division: 'MENS', subDivision: 'MS-L' },
  { name: 'M_ETHNIC_KURTA_FS', mcCode: '111060201', division: 'MENS', subDivision: 'MU' },
  { name: 'M_ETHNIC_LOWER', mcCode: '112040101', division: 'MENS', subDivision: 'MS-L' },
  { name: 'M_ETHNIC_SET', mcCode: '115010101', division: 'MENS', subDivision: 'MU' },
  { name: 'M_FLC_HOODIE_FS', mcCode: '111050501', division: 'MENS', subDivision: 'MU' },
  { name: 'M_FLC_HOODIE_HS', mcCode: '111050401', division: 'MENS', subDivision: 'MU' },
  { name: 'M_FLC_JACKET', mcCode: '111060301', division: 'MENS', subDivision: 'MU' },
  { name: 'M_FLC_LOWER', mcCode: '112040201', division: 'MENS', subDivision: 'MS-L' },
  { name: 'M_FLC_SWEATSHIRT', mcCode: '111050301', division: 'MENS', subDivision: 'MU' },
  { name: 'M_INNERWEAR_BRIEF', mcCode: '116010101', division: 'MENS', subDivision: 'MS-IW' },
  { name: 'M_INNERWEAR_TRUNK', mcCode: '116010201', division: 'MENS', subDivision: 'MS-IW' },
  { name: 'M_INNERWEAR_VEST', mcCode: '116010301', division: 'MENS', subDivision: 'MS-IW' },
  { name: 'M_KURTA_FS', mcCode: '111060101', division: 'MENS', subDivision: 'MU' },
  { name: 'M_LOWER_FS', mcCode: '112030101', division: 'MENS', subDivision: 'MS-L' },
  { name: 'M_LOWER_HS', mcCode: '113040101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_LOWER_HS_JOGGER', mcCode: '113040201', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_LOWER_JOGGER_FS', mcCode: '112030201', division: 'MENS', subDivision: 'MS-L' },
  { name: 'M_ML_BERMUDA', mcCode: '114030101', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_CARGO_TROUSER', mcCode: '114010301', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_ETHNIC_SET', mcCode: '114050101', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_FLC_HOODIE_FS', mcCode: '114020501', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_FLC_HOODIE_HS', mcCode: '114020401', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_FLC_JACKET', mcCode: '114040301', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_FLC_LOWER', mcCode: '114030301', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_FLC_SWEATSHIRT', mcCode: '114020301', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_KURTA_FS', mcCode: '114040101', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_LOWER', mcCode: '114030201', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_LOWER_JOGGER', mcCode: '114030401', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_PW_SHIRT_FS', mcCode: '114010101', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_PW_SHIRT_HS', mcCode: '114010201', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_T_SHIRT_FS', mcCode: '114020201', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_T_SHIRT_HS', mcCode: '114020101', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_TROUSER', mcCode: '114010101', division: 'MENS', subDivision: 'ML' },
  { name: 'M_ML_TROUSER_JOGGER', mcCode: '114010401', division: 'MENS', subDivision: 'ML' },
  { name: 'M_MW_BERMUDA', mcCode: '117030101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_CARGO_TROUSER', mcCode: '117010201', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_ETHNIC_SET', mcCode: '117050101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_FLC_HOODIE_FS', mcCode: '117020501', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_FLC_HOODIE_HS', mcCode: '117020401', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_FLC_JACKET', mcCode: '117040201', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_FLC_LOWER', mcCode: '117030201', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_FLC_SWEATSHIRT', mcCode: '117020301', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_KURTA_FS', mcCode: '117040101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_LOWER', mcCode: '117030101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_LOWER_JOGGER', mcCode: '117030301', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_PW_SHIRT_FS', mcCode: '117010101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_PW_SHIRT_HS', mcCode: '117010201', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_T_SHIRT_FS', mcCode: '117020201', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_T_SHIRT_HS', mcCode: '117020101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_TROUSER', mcCode: '117010101', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MW_TROUSER_JOGGER', mcCode: '117010301', division: 'MENS', subDivision: 'MW' },
  { name: 'M_MO_BERMUDA', mcCode: '118030101', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_CARGO_TROUSER', mcCode: '118010201', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_FLC_HOODIE_FS', mcCode: '118020501', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_FLC_HOODIE_HS', mcCode: '118020401', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_FLC_JACKET', mcCode: '118040201', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_FLC_LOWER', mcCode: '118030201', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_FLC_SWEATSHIRT', mcCode: '118020301', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_LOWER', mcCode: '118030101', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_LOWER_JOGGER', mcCode: '118030301', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_PW_SHIRT_FS', mcCode: '118010101', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_PW_SHIRT_HS', mcCode: '118010201', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_T_SHIRT_FS', mcCode: '118020201', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_T_SHIRT_HS', mcCode: '118020101', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_TROUSER', mcCode: '118010101', division: 'MENS', subDivision: 'MO' },
  { name: 'M_MO_TROUSER_JOGGER', mcCode: '118010301', division: 'MENS', subDivision: 'MO' },
  { name: 'M_PW_SHIRT_FS', mcCode: '111030101', division: 'MENS', subDivision: 'MU' },
  { name: 'M_PW_SHIRT_HS', mcCode: '111030201', division: 'MENS', subDivision: 'MU' },
  { name: 'M_SHORTS_HS', mcCode: '113010201', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_SPORTS_SHIRT_FS', mcCode: '113050101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_SPORTS_SHIRT_HS', mcCode: '113050201', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_T_SHIRT_FS', mcCode: '111020201', division: 'MENS', subDivision: 'MU' },
  { name: 'M_T_SHIRT_HS', mcCode: '111020101', division: 'MENS', subDivision: 'MU' },
  { name: 'M_TEES_FS', mcCode: '113040101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_TEES_HS', mcCode: '113010101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_TIGHTS_FS', mcCode: '113020101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_TIGHTS_HS', mcCode: '113010101', division: 'MENS', subDivision: 'MS-U' },
  { name: 'M_TROUSER_FS', mcCode: '112010101', division: 'MENS', subDivision: 'MS-L' },
  { name: 'M_TROUSER_FS_JOGGER', mcCode: '112020101', division: 'MENS', subDivision: 'MS-L' },
];

async function main() {
  console.log('Starting major category seeding from BOARDER MENU ADD.xlsx...');

  // Find or verify the major_category master attribute exists
  const masterAttr = await prisma.masterAttribute.findUnique({
    where: { key: 'major_category' }
  });

  if (!masterAttr) {
    console.error('ERROR: MasterAttribute with key "major_category" not found in DB.');
    console.error('Please run the base seed first.');
    process.exit(1);
  }

  console.log(`Found MasterAttribute: ${masterAttr.label} (ID: ${masterAttr.id})`);

  // Clean replace: delete all existing allowed values for major_category
  const deleted = await prisma.attributeAllowedValue.deleteMany({
    where: { attributeId: masterAttr.id }
  });
  console.log(`Deleted ${deleted.count} old major category values`);

  // Insert all 308 new values
  const data = MAJOR_CATEGORIES.map((cat, index) => ({
    attributeId: masterAttr.id,
    shortForm: cat.name,
    fullForm: cat.name,
    aliases: [cat.mcCode, cat.division, cat.subDivision],
    displayOrder: index,
    isActive: true,
  }));

  await prisma.attributeAllowedValue.createMany({ data });

  console.log(`Inserted ${data.length} major category values`);
  console.log('Done.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
